// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fitness-charts/BarWorkouts.tsx": () => import("../components/mockups/fitness-charts/BarWorkouts.tsx"),
  "./components/mockups/fitness-charts/DonutGoal.tsx": () => import("../components/mockups/fitness-charts/DonutGoal.tsx"),
  "./components/mockups/fitness-charts/FunnelAdherence.tsx": () => import("../components/mockups/fitness-charts/FunnelAdherence.tsx"),
  "./components/mockups/fitness-charts/HeatmapStreak.tsx": () => import("../components/mockups/fitness-charts/HeatmapStreak.tsx"),
  "./components/mockups/fitness-charts/LineDistance.tsx": () => import("../components/mockups/fitness-charts/LineDistance.tsx"),
  "./components/mockups/fitness-charts/SparklineHR.tsx": () => import("../components/mockups/fitness-charts/SparklineHR.tsx"),
  "./components/mockups/fitness-charts/StatDistance.tsx": () => import("../components/mockups/fitness-charts/StatDistance.tsx"),
  "./components/mockups/fitness-charts/TableRecent.tsx": () => import("../components/mockups/fitness-charts/TableRecent.tsx")
};
